neilenns/ambientweather2mqtt

- README.md
- src/ambientWeatherHandler.ts
- src/sensorNames.ts
- src/sensors.ts
> Add winddir

- src/ambientWeatherHandler.ts
> Send zero values instead of skipping them

- CHANGELOG.md
> Prepare for initial release

- src/main.ts
- src/sensor.ts
- src/weatherDataHandler.ts
> Only send discovery when sensors exist

- src/SensorDataPayload.ts
- src/sensor.ts
- src/weatherDataHandler.ts
> Stop sending values as JSON

- src/sensor.ts
- src/sensorDiscoveryPayload.ts
> Remove connections property from auto-discovery

- postman/Ambient Weather.postman_collection.json
> Fix dateutc param name in postman

- src/controllers/weatherDataController.ts
- src/entity.ts
> Fix incoming UTC date to local timezone issue

- .github/workflows/release.yml
> Publish the Docker image to GitHub Package repository

- README.md
Tiny update to fix `docker-compose` command.
> Fix docker-compose command

- README.md
> Readme file is busted

- hassio_aw2m/config.yaml
> Update hassio version

- .github/workflows/dependabot.yml
> Add dependabot for github actions

- src/controllers/weatherDataController.ts
Fixes #90 
Looks like I forgot to add processing the specific temp values from the data stream. Oops.
> Add missing temp values to data processing

- src/controllers/weatherDataController.ts
Fixes #106
Check for date conversion faliure and use actual current time instead if it happens.
> Handle invalid incoming dates

- .vscode/settings.json
- README.md
- src/binarySensor.ts
- src/mqttManager.ts
- src/sensor.ts
- src/topicRoot.ts
- src/types/environment.d.ts
> Provide an environment variable to set the topic root

- CHANGELOG.md
- DEVELOPMENT.md
- README.md
- src/controllers/weatherDataController.ts
- src/entityManager.ts
- src/entityNames.ts
- src/sensorUnit.ts
> Add support for Ambient Weather lightning sensors

- DEVELOPMENT.md
- README.md
- src/controllers/weatherDataController.ts
- src/entityManager.ts
- src/entityNames.ts
> Add support for AQIN indoor sensor

- package-lock.json
- package.json
- src/binarySensor.ts
- src/calculations.ts
- src/controllers/mqttDiscoveryController.ts
- src/controllers/weatherDataController.ts
- src/entity.ts
- src/entityManager.ts
- src/main.ts
- src/mqttManager.ts
- src/sensor.ts
- src/utilities.ts
- src/webServer.ts
- test/calculatedSensors.spec.ts
- tsconfig.json
> Upgrade TypeScript and node module resolutions

- src/calculations.ts
> Truncate calculated values to two decimal places

- .github/workflows/docker-image.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
> Update to new versions of the github actions

- .mocharc.jsonc
- package-lock.json
- package.json
- src/entityManager.ts
- src/env.ts
- src/main.ts
- src/mqttManager.ts
- src/topicRoot.ts
- src/webServer.ts
- test/test.env
> Use zod to process environment variables

- DEVELOPMENT.md
- README.md
- src/controllers/weatherDataController.ts
- src/entityManager.ts
- src/entityNames.ts
> Add "yearlyrainin" sensor

- renovate.json
> Switch to renovatebot

- Dockerfile
- hassio_aw2m/config.yaml
- sampleConfiguration/.env
- src/env.ts
- src/log.ts
> Properly support timezone in log messages

- Dockerfile
> Fix use of `--no-optional`
